language: python

python:
  - "2.7"

git:
  depth: 10

notifications:
  email: false

services:
  - docker

install:
  - pip install --upgrade pip
  - pip install pandas numpy matplotlib requests

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - (cd testing && make test_all)
